general {
  lock_cmd         = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session # garante lock antes de suspender
  after_sleep_cmd = hyprctl dispatch dpms on # opcional: reacende monitores ao acordar
}

# # Listener 1: Bloqueia a tela após 5 minutos (300s)
# listener {
#   timeout     = 300
#   on-timeout  = loginctl lock-session
# }

# Listener 3: Suspende o PC após 5.5 minutos (330s)
# Se você não mexer após o lock, ele suspenderá 30s depois
listener {
    timeout = 300
    on-timeout = systemctl suspend
}

# Listener 2: Desliga o monitor logo após bloquear (opcional, economiza bateria)
listener {
    timeout = 305
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
