#################
### AUTOSTART ###
#################

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprctl setcursor "everforest-cursors-light" 30
exec-once = awww-daemon
exec-once = waybar
exec-once = swaync
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = wl-paste --type text --watch cliphist store 
# exec-once = wl-paste --type image --watch cliphist store
exec-once = clipse -listen
exec-once = wl-clip-persist --clipboard regular
exec-once = gnome-keyring-daemon --start --components=secrets 
exec-once = nm-applet --indicator
exec-once = rclone mount gdrive: ~/GoogleDrive --vfs-cache-mode writes
exec-once = pika-backup --gapplication-service

exec-once = hypridle

# OSD server
exec-once = swayosd-server

# exec-once = wayscriber --daemon

# exec-once = handy --start-hidden
