windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Initialize apps on workspaces
windowrule = match:initial_class ^(Spotify)$, workspace 3

# Floating windows apps
windowrule = match:class clipse, float true
windowrule = match:class clipse, size 622 652

windowrule = match:class nwg-look, float true
windowrule = match:class nwg-look, size 822 682

windowrule = match:class nm-connection-editor, float true
windowrule = match:class nm-connection-editor, size 822 682

windowrule = match:class blueman-manager, float true
windowrule = match:class blueman-manager, size 822 682

windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float true
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size 822 682
